/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/firebase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin authenticate with Firebase
         * @description Exchange a Firebase ID token for admin JWT tokens. The email must exist in admin_users table.
         */
        post: operations["admin_AdminAuthController_firebaseAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh admin access token */
        post: operations["admin_AdminAuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin logout and invalidate refresh token */
        post: operations["admin_AdminAuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users with pagination and filters */
        get: operations["admin_AdminUsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user details by ID */
        get: operations["admin_AdminUsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user subscription status (Super Admin only) */
        patch: operations["admin_AdminUsersController_updateSubscription"];
        trace?: never;
    };
    "/api/v1/admin/subscriptions/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all plans including inactive */
        get: operations["admin_AdminSubscriptionsController_getPlansAdmin"];
        put?: never;
        /** Create a new plan (Super Admin only) */
        post: operations["admin_AdminSubscriptionsController_createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/subscriptions/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate a plan (Super Admin only) */
        delete: operations["admin_AdminSubscriptionsController_deactivatePlan"];
        options?: never;
        head?: never;
        /** Update a plan (Super Admin only) */
        patch: operations["admin_AdminSubscriptionsController_updatePlan"];
        trace?: never;
    };
    "/api/v1/admin/subscriptions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subscription statistics */
        get: operations["admin_AdminSubscriptionsController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/promo-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all promo codes with pagination */
        get: operations["admin_AdminPromoCodesController_findAll"];
        put?: never;
        /** Create a new promo code */
        post: operations["admin_AdminPromoCodesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/promo-codes/{id}/redemptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get redemptions for a promo code */
        get: operations["admin_AdminPromoCodesController_getRedemptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/promo-codes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate a promo code */
        delete: operations["admin_AdminPromoCodesController_deactivate"];
        options?: never;
        head?: never;
        /** Update a promo code */
        patch: operations["admin_AdminPromoCodesController_update"];
        trace?: never;
    };
    "/api/v1/admin/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard overview metrics */
        get: operations["admin_DashboardController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user registration growth over time */
        get: operations["admin_DashboardController_getGrowth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get check-ins per day */
        get: operations["admin_DashboardController_getCheckIns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get revenue and subscriber metrics */
        get: operations["admin_DashboardController_getRevenue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics/mood-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get mood score distribution (low/medium/high) */
        get: operations["admin_AnalyticsController_getMoodDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cohort retention metrics */
        get: operations["admin_AnalyticsController_getRetention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics/feature-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get feature usage statistics */
        get: operations["admin_AnalyticsController_getFeatureUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics/conversion-funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get conversion funnel metrics */
        get: operations["admin_AnalyticsController_getConversionFunnel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/analytics/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top themes from journals */
        get: operations["admin_AnalyticsController_getThemes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system health status */
        get: operations["admin_SystemController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API cost tracking (placeholder) */
        get: operations["admin_SystemController_getCosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent failed webhook events */
        get: operations["admin_SystemController_getErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get recent webhook events */
        get: operations["admin_SystemController_getWebhooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/webhooks/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed webhook event (Super Admin only) */
        post: operations["admin_SystemController_retryWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FirebaseAuthDto: {
            /**
             * @description Firebase ID token from the client SDK
             * @example eyJhbGciOiJSUzI1NiIsImtpZCI6...
             */
            id_token: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            name: Record<string, never> | null;
            avatar_url: Record<string, never> | null;
            /** @enum {string} */
            subscription_status: "free" | "pro" | "cancelled" | "paused" | "past_due";
            /** @description Whether the user has completed onboarding */
            is_onboarded: boolean;
            /** @enum {string|null} */
            gender: "male" | "female" | "non_binary" | "prefer_not_to_say" | null;
            date_of_birth: Record<string, never> | null;
        };
        AuthResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            access_token: string;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refresh_token: string;
            user: components["schemas"]["AuthUserDto"];
        };
        OnboardingDto: {
            /**
             * @description User display name
             * @example Devansh
             */
            name: string;
            /**
             * @description Date of birth (YYYY-MM-DD)
             * @example 1998-05-15
             */
            date_of_birth: string;
            /**
             * @description Gender
             * @example male
             * @enum {string}
             */
            gender: "male" | "female" | "non_binary" | "prefer_not_to_say";
            /**
             * @description User timezone
             * @example Asia/Kolkata
             */
            timezone?: string;
        };
        RefreshTokenDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            refresh_token: string;
        };
        AdminAuthResponseDto: {
            access_token: string;
            refresh_token: string;
            admin: Record<string, never>;
        };
        UpdateUserDto: {
            /** @description User display name */
            name?: string;
            /** @description Avatar URL */
            avatar_url?: string;
            /** @description User timezone (e.g. Asia/Kolkata) */
            timezone?: string;
        };
        UpdateFcmTokenDto: {
            /** @description Firebase Cloud Messaging token for push notifications */
            fcm_token: string;
        };
        UpdateSubscriptionDto: {
            /**
             * @description Subscription status
             * @enum {string}
             */
            subscription_status: "free" | "pro" | "cancelled" | "paused" | "past_due";
        };
        CreateTaskDto: {
            /**
             * @description Task title
             * @example Buy groceries
             */
            title: string;
            /** @description Task description */
            description?: string;
            /**
             * @description Scheduled date
             * @example 2026-02-20
             */
            scheduled_date: string;
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
            /**
             * @description Task source
             * @default manual
             */
            source: string;
        };
        UpdateTaskDto: {
            /** @description Task title */
            title?: string;
            /** @description Task description */
            description?: string;
            /**
             * @description Scheduled date
             * @example 2026-02-20
             */
            scheduled_date?: string;
            /** @enum {string} */
            priority?: "low" | "medium" | "high";
            /** @enum {string} */
            status?: "pending" | "completed" | "rolled_over" | "cancelled";
        };
        RolloverTaskDto: {
            /**
             * @description New date for the rolled-over task
             * @example 2026-02-21
             */
            new_date: string;
        };
        CreateNoteDto: {
            /**
             * @description Note content
             * @example Call dentist tomorrow
             */
            content: string;
            /**
             * @description Follow-up date
             * @example 2026-02-20
             */
            follow_up_date?: string;
            /**
             * @description Note source
             * @default manual
             * @enum {string}
             */
            source: "voice" | "manual";
        };
        UpdateNoteDto: {
            /** @description Note content */
            content?: string;
            /**
             * @description Follow-up date
             * @example 2026-02-20
             */
            follow_up_date?: string;
            /** @description Whether the note is resolved */
            is_resolved?: boolean;
        };
        TranscriptMessageDto: {
            /**
             * @description Role (user/assistant)
             * @example user
             */
            role: string;
            /**
             * @description Message text
             * @example Hello
             */
            text: string;
            /**
             * @description Timestamp in seconds
             * @example 0
             */
            timestamp: number;
        };
        SaveConversationDto: {
            /**
             * @description ElevenLabs conversation ID
             * @example conv_abc123
             */
            conversation_id: string;
            /**
             * @description Transcript array
             * @example [
             *       {
             *         "role": "user",
             *         "text": "Hello",
             *         "timestamp": 0
             *       },
             *       {
             *         "role": "assistant",
             *         "text": "Hi there!",
             *         "timestamp": 1
             *       }
             *     ]
             */
            transcript: components["schemas"]["TranscriptMessageDto"][];
            /**
             * @description Duration in seconds
             * @example 120
             */
            duration_seconds: number;
            /**
             * @description Date of conversation (defaults to today)
             * @example 2026-02-15
             */
            date?: string;
        };
        CreateSubscriptionDto: {
            /** @description Subscription plan UUID */
            plan_id: string;
            /** @description Promo code for discount */
            promo_code?: string;
        };
        VerifyPaymentDto: {
            /** @description Razorpay payment ID */
            razorpay_payment_id: string;
            /** @description Razorpay subscription ID */
            razorpay_subscription_id: string;
            /** @description Razorpay signature for verification */
            razorpay_signature: string;
        };
        CreatePlanDto: {
            /**
             * @description Plan name
             * @example Pro Monthly
             */
            name: string;
            /**
             * @description Price in paise
             * @example 99900
             */
            price_amount: number;
            /**
             * @description Currency code
             * @default INR
             */
            currency: string;
            /**
             * @description Billing interval
             * @enum {string}
             */
            interval: "monthly" | "yearly";
            /** @description Plan features as key-value pairs */
            features?: Record<string, never>;
            /**
             * @description Whether plan is active
             * @default true
             */
            is_active: boolean;
        };
        UpdatePlanDto: {
            /**
             * @description Plan name
             * @example Pro Monthly
             */
            name?: string;
            /**
             * @description Price in paise
             * @example 99900
             */
            price_amount?: number;
            /**
             * @description Currency code
             * @default INR
             */
            currency: string;
            /**
             * @description Billing interval
             * @enum {string}
             */
            interval?: "monthly" | "yearly";
            /** @description Plan features as key-value pairs */
            features?: Record<string, never>;
            /**
             * @description Whether plan is active
             * @default true
             */
            is_active: boolean;
        };
        RedeemPromoDto: {
            /**
             * @description Promo code to redeem
             * @example SAVE20
             */
            code: string;
        };
        CreatePromoDto: {
            /**
             * @description Promo code (stored uppercase)
             * @example SAVE20
             */
            code: string;
            /**
             * @description Discount type
             * @enum {string}
             */
            type: "percentage" | "flat" | "set_price";
            /**
             * @description Value: percentage (1-100), flat amount in paise, or set price in paise
             * @example 20
             */
            value: number;
            /**
             * @description Subscription duration in months when redeemed
             * @example 12
             */
            duration_months?: number;
            /**
             * @description Maximum number of redemptions allowed
             * @example 100
             */
            max_uses?: number;
            /**
             * @description Valid from date (ISO 8601)
             * @example 2026-01-01T00:00:00.000Z
             */
            valid_from: string;
            /**
             * @description Valid until date (ISO 8601)
             * @example 2026-12-31T23:59:59.000Z
             */
            valid_until?: string;
            /**
             * @description Whether the promo is active
             * @default true
             */
            is_active: boolean;
        };
        UpdatePromoDto: {
            /**
             * @description Promo code (stored uppercase)
             * @example SAVE20
             */
            code?: string;
            /**
             * @description Discount type
             * @enum {string}
             */
            type?: "percentage" | "flat" | "set_price";
            /**
             * @description Value: percentage (1-100), flat amount in paise, or set price in paise
             * @example 20
             */
            value?: number;
            /**
             * @description Subscription duration in months when redeemed
             * @example 12
             */
            duration_months?: number;
            /**
             * @description Maximum number of redemptions allowed
             * @example 100
             */
            max_uses?: number;
            /**
             * @description Valid from date (ISO 8601)
             * @example 2026-01-01T00:00:00.000Z
             */
            valid_from?: string;
            /**
             * @description Valid until date (ISO 8601)
             * @example 2026-12-31T23:59:59.000Z
             */
            valid_until?: string;
            /**
             * @description Whether the promo is active
             * @default true
             */
            is_active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_AdminAuthController_firebaseAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FirebaseAuthDto"];
            };
        };
        responses: {
            /** @description Admin auth successful */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthResponseDto"];
                };
            };
            /** @description Invalid Firebase token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No admin account for this email */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminAuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuthResponseDto"];
                };
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminAuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminUsersController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Search by email or name */
                search?: string;
                /** @description Filter by subscription status */
                subscription_status?: "free" | "pro" | "cancelled" | "paused" | "past_due";
                /** @description Sort field */
                sort_by?: string;
                /** @description Sort order */
                sort_order?: "ASC" | "DESC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminUsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details returned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminUsersController_updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionDto"];
            };
        };
        responses: {
            /** @description Subscription updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Super Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminSubscriptionsController_getPlansAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminSubscriptionsController_createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanDto"];
            };
        };
        responses: {
            /** @description Plan created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Super Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminSubscriptionsController_deactivatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deactivated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Super Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminSubscriptionsController_updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plan UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanDto"];
            };
        };
        responses: {
            /** @description Plan updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Super Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminSubscriptionsController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription stats (total pro, free, MRR) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminPromoCodesController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of promo codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminPromoCodesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePromoDto"];
            };
        };
        responses: {
            /** @description Promo code created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error or code already exists */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminPromoCodesController_getRedemptions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Promo code UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of redemptions with user info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Promo code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminPromoCodesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Promo code UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Promo code deactivated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Promo code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AdminPromoCodesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Promo code UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePromoDto"];
            };
        };
        responses: {
            /** @description Promo code updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Promo code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_DashboardController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview metrics returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_DashboardController_getGrowth: {
        parameters: {
            query?: {
                /** @description Number of days to look back (default: 30) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Growth data by date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_DashboardController_getCheckIns: {
        parameters: {
            query?: {
                /** @description Number of days to look back (default: 30) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check-ins data by date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_DashboardController_getRevenue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revenue and plan breakdown */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AnalyticsController_getMoodDistribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mood distribution returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AnalyticsController_getRetention: {
        parameters: {
            query?: {
                /** @description Number of cohort months to analyze (default: 6) */
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retention data by cohort */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AnalyticsController_getFeatureUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Feature usage stats returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AnalyticsController_getConversionFunnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversion funnel returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_AnalyticsController_getThemes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top 20 themes with counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_SystemController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_SystemController_getCosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost breakdown returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_SystemController_getErrors: {
        parameters: {
            query?: {
                /** @description Max number of events to return (default: 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of error webhook events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_SystemController_getWebhooks: {
        parameters: {
            query?: {
                /** @description Max number of events to return (default: 50) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of webhook events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_SystemController_retryWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Webhook event UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook reprocessed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - Super Admin required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
